# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FloatingActionAnimation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FloatingActionAnimation


pod 'VBFPopFlatButton'
pod 'Floaty'

end
